install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo sed -i 's/precise/trusty/g' /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install --only-upgrade dpkg
  - sudo sed -i 's/trusty/vivid/g' /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools
  - sudo apt-get install g++-4.8
  - sudo apt-get install catch


script:
  - qmake armadill.pro
  - make
  - ./armadill-server -t
